### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [0]:
import tensorflow as tf
#tf.enable_eager_execution()
tf.set_random_seed(42)

In [2]:
tf.__version__

'1.15.0'

#### 

### Collect Data

In [3]:
import keras

Using TensorFlow backend.


In [4]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


In [5]:
print(testY[0:5])

[9 2 1 1 6]


In [8]:
trainX.shape

(60000, 28, 28)

In [9]:
trainY.shape

(60000,)

### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [0]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [11]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Visualize the data

Plot first 10 images in the triaining set and their labels.

In [32]:
print (trainX[:10,:])
print (trainY[:10])

[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ... 180   0   0]
  [  0   0   0 ...  72   0   0]
  [  0   0   0 ...  70   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...  39   1   0]
  ...
  [  0   0   0 ... 238   0   0]
  [  0   0   0 ... 131   0   0]
  [  0   0   0 ...   0   0  

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [0]:
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Execute the model using model.fit()

In [18]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=10)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 56us/sample - loss: 0.5975 - acc: 0.7958 - val_loss: 0.5192 - val_acc: 0.8185
Epoch 2/10
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4924 - acc: 0.8310 - val_loss: 0.4978 - val_acc: 0.8312
Epoch 3/10
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4664 - acc: 0.8382 - val_loss: 0.4759 - val_acc: 0.8343
Epoch 4/10
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4556 - acc: 0.8427 - val_loss: 0.4689 - val_acc: 0.8359
Epoch 5/10
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4487 - acc: 0.8452 - val_loss: 0.4695 - val_acc: 0.8368
Epoch 6/10
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4446 - acc: 0.8451 - val_loss: 0.4728 - val_acc: 0.8367
Epoch 7/10
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4393 - acc: 0.8482 - val_loss: 0.

### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [0]:
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Execute the model

In [20]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=15,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 3s 57us/sample - loss: 0.5996 - acc: 0.7934 - val_loss: 0.5211 - val_acc: 0.8206
Epoch 2/15
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4896 - acc: 0.8329 - val_loss: 0.4862 - val_acc: 0.8324
Epoch 3/15
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4689 - acc: 0.8400 - val_loss: 0.4737 - val_acc: 0.8350
Epoch 4/15
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4567 - acc: 0.8417 - val_loss: 0.4756 - val_acc: 0.8367
Epoch 5/15
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4520 - acc: 0.8438 - val_loss: 0.4683 - val_acc: 0.8371
Epoch 6/15
60000/60000 [==============================] - 3s 54us/sample - loss: 0.4451 - acc: 0.8473 - val_loss: 0.4666 - val_acc: 0.8376
Epoch 7/15
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4407 - acc: 0.8472 - val_loss: 0.

### Customize the learning rate to 0.001 in sgd optimizer and run the model

In [0]:
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.001)

In [0]:
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=15,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 4s 60us/sample - loss: 0.4107 - acc: 0.8561 - val_loss: 0.4613 - val_acc: 0.8436
Epoch 2/15
60000/60000 [==============================] - 3s 57us/sample - loss: 0.4061 - acc: 0.8587 - val_loss: 0.4587 - val_acc: 0.8437
Epoch 3/15
60000/60000 [==============================] - 3s 56us/sample - loss: 0.4089 - acc: 0.8565 - val_loss: 0.4701 - val_acc: 0.8419
Epoch 4/15
60000/60000 [==============================] - 3s 56us/sample - loss: 0.4067 - acc: 0.8588 - val_loss: 0.4631 - val_acc: 0.8439
Epoch 5/15
60000/60000 [==============================] - 3s 56us/sample - loss: 0.4061 - acc: 0.8589 - val_loss: 0.4651 - val_acc: 0.8428
Epoch 6/15
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4062 - acc: 0.8572 - val_loss: 0.4645 - val_acc: 0.8440
Epoch 7/15
60000/60000 [==============================] - 3s 55us/sample - loss: 0.4070 - acc: 0.8579 - val_loss: 0.

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [0]:
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

In [0]:
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))


#Add 1st Hidden Layer which provides 100 Outputs after applying sigmoid
model.add(tf.keras.layers.Dense(100, activation='sigmoid'))

#Add 2nd Hidden Layer which provides 100 Outputs after applying sigmoid
model.add(tf.keras.layers.Dense(100, activation='sigmoid'))

#Add 3rd Hidden Layer which provides 10 Outputs after applying sigmoid
model.add(tf.keras.layers.Dense(10, activation='sigmoid'))

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [26]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=15,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 4s 69us/sample - loss: 1.8450 - acc: 0.3948 - val_loss: 1.3115 - val_acc: 0.5550
Epoch 2/15
60000/60000 [==============================] - 4s 73us/sample - loss: 1.1436 - acc: 0.6182 - val_loss: 1.0558 - val_acc: 0.6059
Epoch 3/15
60000/60000 [==============================] - 4s 68us/sample - loss: 1.0618 - acc: 0.6302 - val_loss: 1.0605 - val_acc: 0.6218
Epoch 4/15
60000/60000 [==============================] - 4s 62us/sample - loss: 1.0420 - acc: 0.6250 - val_loss: 1.0727 - val_acc: 0.6086
Epoch 5/15
60000/60000 [==============================] - 4s 62us/sample - loss: 1.0611 - acc: 0.6051 - val_loss: 1.0383 - val_acc: 0.6284
Epoch 6/15
60000/60000 [==============================] - 4s 62us/sample - loss: 1.0405 - acc: 0.6025 - val_loss: 1.0432 - val_acc: 0.6032
Epoch 7/15
60000/60000 [==============================] - 4s 61us/sample - loss: 1.0857 - acc: 0.5764 - val_loss: 1.

## Review model

In [27]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_5 (Reshape)          (None, 784)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_6 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_7 (Dense)              (None, 10)                1010      
_________________________________________________________________
dense_8 (Dense)              (None, 10)                110       
Total params: 89,720
Trainable params: 89,720
Non-trainable params: 0
_________________________________________________________________


### Run the model

In [0]:
Model was run before Summary. 