### Build a DNN using Keras with `RELU` and `ADAM`

In [0]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 63kB/s 
     |████████████████████████████████| 450kB 23.3MB/s 
     |████████████████████████████████| 3.8MB 41.7MB/s 
     |████████████████████████████████| 81kB 10.4MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstall

#### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'2.0.0'

In [0]:
import keras

Using TensorFlow backend.


#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


#### Change train and test labels into one-hot vectors

In [0]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [0]:
print(trainY.shape)
print('TrainY first 5 data: ', trainY[0:5])

(60000, 10)
TrainY first 5 data:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
tf.keras.backend.clear_session()
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))
model.add(tf.keras.layers.BatchNormalization())


#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
#Add Dense Layer which provides 200 Outputs after applying relu
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 100 Outputs after applying relu
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

#Add  dropout layer
model.add(tf.keras.layers.Dropout(0.25))


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:

#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))


#Comile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=15,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 17s 290us/sample - loss: 0.5238 - accuracy: 0.8156 - val_loss: 0.3951 - val_accuracy: 0.8570
Epoch 2/15
60000/60000 [==============================] - 15s 242us/sample - loss: 0.3973 - accuracy: 0.8554 - val_loss: 0.3736 - val_accuracy: 0.8667
Epoch 3/15
60000/60000 [==============================] - 14s 237us/sample - loss: 0.3623 - accuracy: 0.8677 - val_loss: 0.3712 - val_accuracy: 0.8729
Epoch 4/15
60000/60000 [==============================] - 14s 238us/sample - loss: 0.3347 - accuracy: 0.8774 - val_loss: 0.3504 - val_accuracy: 0.8782
Epoch 5/15
60000/60000 [==============================] - 14s 240us/sample - loss: 0.3197 - accuracy: 0.8834 - val_loss: 0.3619 - val_accuracy: 0.8794
Epoch 6/15
60000/60000 [==============================] - 15s 256us/sample - loss: 0.3018 - accuracy: 0.8880 - val_loss: 0.3285 - val_accuracy: 0.8857
Epoch 7/15
60000/60000 [====================

Accuracy after 15 Epochs of batch size 32 is 89.30
